#!/bin/sh
docker run -d \
  -p 127.0.0.1:23080:80 \
  -v /srv/docker/owncloud/apps:/var/lib/owncloud/apps \
  -v /srv/docker/owncloud/data:/var/lib/owncloud/data \
  -v /srv/docker/owncloud/etc/owncloud:/etc/owncloud \
  --name owncloud --restart=always \
  neingeist/owncloud
